### PR TITLE
New quest system

### PR DESCRIPTION
**Pull request by msteiger**
This is an almost complete rewrite of the questing system. See the video for a showcase. This also adds new meshes (question mark/exclamation mark), incorporates the new icon set and a NUI-compatible HUD.

See the commits for more details.

### CODE REVIEW

**Comment by Cervator** [comment]
Awesomesauce :-)

After this would be module be ready for adding to the lineup?

**Comment by msteiger** [comment]
I'd think so, yes.

**Comment by nh-99** [comment]
This looks very cool! Everything I wanted to do and never had time for... thanks for bringing this module up to speed!

**Comment by Cervator** [comment]
On trying to merge this I noticed it still uses the GenericObject system we had merged to engine briefly but then replaced with https://github.com/MovingBlocks/Terasology/pull/1953

@msteiger do you want to update it to the new approach? I'm hoping that's easy

**Pull request merged**
